### ISSUE TITLE
Deriviation without notice or attribution

### ISSUE THREAD

**Issue by jdegoes** [tbrown1979/cancelable-blocking-io#1]
The code in this project looks copy/pasted/modified from ZIO, yet there is no copyright or attribution notice.

I'm sure this was just an oversight, but in the future, if you copy/paste/modify code from any open source project, I'd recommend carrying along copyright notices, performing proper attribution with linkback, and choosing a clearly-compatible license (if different than original).

Thank you!

**Comment by tbrown1979** [comment]
@jdegoes Sorry about this. I made this repo relatively quickly as an example and this was an oversight. I hope I have reasonably addressed your concerns with my latest changes. Again, sorry about that. Let me know if there are any further concerns!

**Comment by jdegoes** [comment]
@tbrown1979 No worries, I assumed as much. Thanks for the update!
